// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7f1F4SIjDNBdIM_j8Je5llYV3LkB4C8',
    appId: '1:209090930821:web:1f4be2b052881f7b7721ec',
    messagingSenderId: '209090930821',
    projectId: 'capstone-fd1ff',
    authDomain: 'capstone-fd1ff.firebaseapp.com',
    storageBucket: 'capstone-fd1ff.appspot.com',
    measurementId: 'G-F2B6H1WSFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1DuOc5YzvvkS5I4KFOxqviaLqmcMvTU',
    appId: '1:209090930821:android:b6bc06c132f048b77721ec',
    messagingSenderId: '209090930821',
    projectId: 'capstone-fd1ff',
    storageBucket: 'capstone-fd1ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Ai_h34Szxyo5zBy0SHjiLwb82ijlSqA',
    appId: '1:209090930821:ios:494ef87ea95a453e7721ec',
    messagingSenderId: '209090930821',
    projectId: 'capstone-fd1ff',
    storageBucket: 'capstone-fd1ff.appspot.com',
    iosBundleId: 'com.example.shapshift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Ai_h34Szxyo5zBy0SHjiLwb82ijlSqA',
    appId: '1:209090930821:ios:83ba142926a6f8cb7721ec',
    messagingSenderId: '209090930821',
    projectId: 'capstone-fd1ff',
    storageBucket: 'capstone-fd1ff.appspot.com',
    iosBundleId: 'com.example.shapshift.RunnerTests',
  );
}
